#!/usr/bin/perl
use strict;
use warnings;
use Term::ANSIColor;

my ($url,$file)=("","");
#my $file="";
my $filename = __FILE__;
$filename =~ s/\.\///;
my @options = qw!+-f -h -u -l!;
my $hello="Blabla";
my $input="";
my $fh=0;
if(!(my $pid = `pgrep tor`)) {
	print color("bold red");
	print "[!] Tor daemon has not been started yet...Aborting!!!\n";
	print color("reset");
	exit -1;
}

if(@ARGV) {
	my @m=@ARGV;
	foreach(@ARGV) {
		if($_ eq '-f') {
			shift(@m);
			$file=shift(@m);
		}
		if($_ eq '-u') {
			shift(@m);
			$url=shift(@m);
		}
		if($_ eq '-h') {
			&usage();			
		}
		if($_ eq '-l') {
			shift(@m);
			$input=shift(@m);
		}
	}
}

if($input ne "") {
	print color("bold green");
	print "[+] Loading list...\n";
	print color("reset");
	print color("bold red");
	open(my $fh,$input) or die("Could not open file '$input' $!\n");
	print color("reset");
	while(my $row=<$fh>) {
		chomp $row;
		system 'proxychains','youtube-dl','-x','--audio-format=mp3',$row;
		print color("reset");
		print "Using URL $row\n";
	}	
	print color("bold green");
	print "[+] Downloading list terminated successfully...\n";
	print color("reset");
}

if($input eq "") {
	print color("reset");
	print "URL: $url\n";
	#if(($file eq "") || ($url eq "")) {
	
	if($url eq "") {
		print color("bold red");
		print "[!] File or URL is not defined...\n";
		print color("reset");
		&usage();
		exit;
	}

#else {
#	&usage();
#	exit;
#}

	system 'proxychains','youtube-dl','-x','--audio-format=mp3',$url;
}

sub usage {
	print "<Usage>: " . $filename . " <Options> [-u|-f|-h]\n
	\t Options:
	\t -u: \t Given URL for download request 
	\t -f: \t Destination filename
	\t -h: \t Show this page\n";
}
